name: Publish Website

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  Build-Artifact-Action:
    name: Build-Artifact-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Upload the artifact
      uses: actions/upload-artifact@v4
      with:
        name: wpcom
        path: |
          .
          !.DS_Store 
          !.stylelintrc.json 
          !.eslintrc 
          !.git 
          !.gitattributes 
          !.github 
          !.gitignore 
          !README.md 
          !composer.json 
          !composer.lock 
          !node_modules 
          !vendor
          !package-lock.json 
          !package.json 
          !.travis.yml 
          !phpcs.xml.dist 
          !sass 
          !style.css.map 
          !yarn.lock